### ISSUE TITLE
Enhance the visual appeal of the task list

### ISSUE THREAD

**Issue by RamtinTJB** [cse110-sp24-group12/warmup-exercise#9]
Things to consider when working on this task:

- Layout and Structure:
  - consistent structure
  - Sectioning the tasks in a meaningful way
  - Adequate whitespace to improve readability
- Typography:
  - Font choice that's readable and engaging (maybe use more than 1 font?)
  - Font size and weight: make sure it's readable
  - Text alignment
- Colors and contrast:
  - Consider color coding the tasks (red for overdue, green for completed, etc.)
  - Consider having background color, borders, .. for the tasks
- Interaction and Feedback
  - Add hover effects
  - Make sure clickable elements stand out somehow
- Anything else that you can think of :)

Not all of these are necessary, but try to consider them as you design the task list to make it look nice!

### Actions Items:
- [x] Change the color scheme of the task list (hover color, page color, ...)
- [x] Have the textbox, date selector, and time selector be on the same row
- [x] Make the tasks slightly narrower so more can fit
- [x] Right adjust the due date in each task
